name             'NodePm2'
maintainer       'Jeevan Dongre'
maintainer_email 'jeevan.dongre@gmail.com'
license          'all_rights'
description      'Installs/Configures node-npm'
long_description 'Installs/Configures node-npm'
version          '0.1.0'

depends 'apt'
depends 'git'
depends 'build-essential'
depends 'application'
depends 'nodejs'
depends 'nginx'

